name: Build Release

on: 
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    uses: Narazaka/vpm-repos/.github/workflows/release.yml@main
    with:
      novcc: false
      repos: https://lilxyzw.github.io/vpm-repos/vpm.json
